config/routes.rb
Rails.application.routes.draw do
  get 'company/new'
  get 'company/create'
  get 'addresses/new'
  get 'addresses/create'
  get 'leads/new'
  get 'leads/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  resources :quotes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'



  get "/home", to: "pages#home"
  get '/residential', to: 'pages#residential'
  get '/commercial', to: 'pages#commercial'
  get '/quote', to: 'pages#quote'



  get '/quotes' => 'quote#index'

  post '/quotes' => 'quotes#create'




  get 'employee/show'

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    can :manage, :all
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end
    if user.supervisor_role?
      can :manage, User
    end
  end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    # can :read, Employee, :email, :last_name, :first_name :title => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
 
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
   
end

app/models/lead.rb
class Lead < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def has_role?(role)
    roles.include?(role)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, :only => [:home]
    skip_before_action :authenticate_user!, :only => [:residential]
    skip_before_action :authenticate_user!, :only => [:commercial]
    skip_before_action :authenticate_user!, :only => [:quotes]
    protected

    #load_and_authorize_resource
    #ROLES = %i[admin moderator author banned]

    #def user_params
      #params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    #end
    
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
  end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def show
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end

    def quote
        
    end

    def residential

    end

    def commercial

    end

end

app/controllers/quote_residential_controller.rb
class CreateQuoteResidential < ActiveRecord: :Migration[5.2]
    def change
        create_table :residentialQuote do |t|
            t.int :residentialApp
            t.int :residentialFloor
            t.int :residentialBasement
            
            t.int :elevatorAmount
            t.int :elevatorUnitPrice
            t.int :elevatorTotalPrice
            t.int :installationFees
            t.int :finalPrice
        end
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @quote = Quote.find(params[:id])
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create

    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:building_type, :number_appartement, :number_floor, :number_basement, :number_compagny, :number_corporate, :number_elevator, :number_parking, :max_occupancy, :business_hour, :building_prices, :elevator_type, :ele_amount, :ele_price_unit, :ele_total_price, :inst_fee, :final_price)
    end


end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end
  
    # POST /resource/unlock
    # def create
    #   super
    # end
  
    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end
  
    # protected
  
    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end
  
    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/employee/show.html.erb
<h1>Employee#show</h1>

<%= form_for :employee, class: 'from-horizontal' do |f| %>

  <div class="form-groupe">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id, autofocus: true, autocomplete: "user_id" %>
  </div>

  <div class="form-groupe">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
  </div>

  <div class="form-groupe">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
  </div>

  <div class="form-groupe">
    <%= f.label :title %><br />
    <%= f.text_field :title, autocomplete: "title" %>
  </div>

<% end %>

app/views/leads/create.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/leads/create.html.erb</p>



<!-- wrapper -->
<div id="ctnWhite"> 
		<div id="wrapper">

			<hr class="m-0" /><!-- 1px line separator -->


			<!-- BUTTON CALLOUT -->
			<a href="./index.html#contact" class="btn btn-xlg btn-danger	 fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Did Rocket Elevator convinced you? 
					<strong>Contact us &raquo;</strong>
				</span>
			</a>
			<!-- /BUTTON CALLOUT -->

		
						<!-- FORM -->
						<div class="col-md-10 col-sm-4" style="margin: 100px 8%;">

							<h3 style="text-align: center;">A Work Faithful To The Wait</h3>

							<!-- Alert Success -->
							<div id="alert_success" class="alert alert-success mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Thank You!</strong> Your message successfully sent!
							</div><!-- /Alert Success -->


							<!-- Alert Failed -->
							<div id="alert_failed" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>[SMTP] Error!</strong> Internal server error!
							</div><!-- /Alert Failed -->


							<!-- Alert Mandatory -->
							<div id="alert_mandatory" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Sorry!</strong> You need to complete all mandatory (*) fields!
							</div><!-- /Alert Mandatory -->



							
							<!-- FORM QUOTE -->
						
								<fieldset>
									<input type="hidden" name="action" value="contact_send" />

									
									<div id="div">
										<div id="number-of-apartments" class="col-md-4">
                                            <%= form.label :number_appartement %>
                                            <%= form.text_field :number_appartement, id: 'number_appartement' %>
										</div>
										<div id="number-of-floors" class="col-md-4">
                                            <%= form.label :number_floor %>
                                            <%= form.text_field :number_floor, id: 'number_floor' %>
										</div>
										<div id="number-of-basements" class="col-md-4">
                                            <%= form.label :number_basement %>
                                            <%= form.text_field :number_basement, id: 'number_basement' %>
										</div>
										<div id="number-of-companies" class="col-md-4">
                                            <%= form.label :number_compagny %>
                                            <%= form.text_field :number_compagny, id: 'number_compagny' %>
										</div>
										<div id="number-of-corporations" class="col-md-4">
                                            <%= form.label :number_corporate %>
                                            <%= form.text_field :number_corporate, id: 'number_corporate' %>
										</div>
										<div id="number-of-elevators" class="col-md-4">
                                            <%= form.label :number_elevator %>
                                            <%= form.text_field :number_elevator, id: 'number_elevator' %>					
										</div>
										<div id="number-of-parking-spots" class="col-md-4">
                                            <%= form.label :number_parking %>
                                            <%= form.text_field :number_parking, id: 'number_parking' %>
										</div>
										<div id="maximum-occupancy" class="corporateChanger col-md-4">
                                            <%= form.label :max_occupancy %>
                                            <%= form.text_field :max_occupancy, id: 'max_occupancy' %>				
										</div>
										<div id="business-hours" class="col-md-4">
                                            <%= form.label :business_hour %>
                                            <%= form.text_field :business_hour, id: 'business_hour' %>							
										</div>
									</div>
								</fieldset>

							<!-- FORM RADIO BUTTON -->

								<div style="margin-top: 50px;" class="priceShow">
									Number of elevator shafts required : <span id="elevatorShafts">0</span>
								</div>


								<div id="elevator_type" class="priceShow"> 
									<div class="row" style="margin-top: 100px;">
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                            <%= form.label :Standard %>
                                            <%= form.radio_button :elevator_type, 'standard' %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                            <%= form.label :Premium %>
                                            <%= form.radio_button :elevator_type, 'premium' %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                            <%= form.label :Excelium %>
                                            <%= form.radio_button :elevator_type, 'excelium' %>
										</div>
									</div>
								</div>
							<!-- FORM RADIO BUTTON -->

							<!-- FORM RADIO VALUE -->

								<div id="quote" class="row" style="margin-top: 130px;">
									<div id="elevator-amount" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                        <%= form.label :ele_amount %>
                                        <%= form.text_field :ele_amount, id: 'ele_amount' %>
									</div>
									<div id="elevator-unit-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                        <%= form.label :ele_price_unit %>
                                        <%= form.text_field :ele_price_unit, id: 'ele_price_unit' %>
									</div>
									<div id="elevator-total-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                        <%= form.label :ele_total_price %>
                                        <%= form.text_field :ele_total_price, id: 'ele_total_price' %>
									</div>
									<div id="installation-fees" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                        <%= form.label :inst_fee %>
                                        <%= form.text_field :inst_fee, id: 'inst_fee' %>
									</div>
									<div id="final-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
                                        <%= form.label :final_price %>
                                        <%= form.text_field :final_price, id: 'final_price' %>
									</div>
									<div class="actions">
                                        <%= form.submit %>
                                    </div>
								</div>
				
						</div>
		</div>
</div>
						<!-- FORM RADIO

app/views/leads/new.html.erb
<h1>Leads#new</h1>
<p>Find me in app/views/leads/new.html.erb</p>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %> 
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  


<!-- wrapper -->
<div id="ctnWhite"> 
		<div id="wrapper">

			<hr class="m-0" /><!-- 1px line separator -->


			<!-- BUTTON CALLOUT -->
			<a href="./index.html#contact" class="btn btn-xlg btn-danger	 fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Did Rocket Elevator convinced you? 
					<strong>Contact us &raquo;</strong>
				</span>
			</a>
			<!-- /BUTTON CALLOUT -->

		
						<!-- FORM -->
						<div class="col-md-10 col-sm-4" style="margin: 100px 8%;">

							<h3 style="text-align: center;">A Work Faithful To The Wait</h3>

							<!-- Alert Success -->
							<div id="alert_success" class="alert alert-success mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Thank You!</strong> Your message successfully sent!
							</div><!-- /Alert Success -->


							<!-- Alert Failed -->
							<div id="alert_failed" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>[SMTP] Error!</strong> Internal server error!
							</div><!-- /Alert Failed -->


							<!-- Alert Mandatory -->
							<div id="alert_mandatory" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Sorry!</strong> You need to complete all mandatory (*) fields!
							</div><!-- /Alert Mandatory -->



							
							<!-- FORM QUOTE -->
						
								<fieldset>
									<input type="hidden" name="action" value="contact_send" />

									<div class="row">
										<div class="col-md-12">
											<select id="building_type" class="form-control pointer" name="contact[department]">		
												<option value="select">--- Select ---</option>
												<option value="residential">Residential</option>
												<option value="commercial">Commercial</option>
												<option value="corporate">Corporate</option>
												<option value="hybrid">Hybrid</option>
											</select>
										</div>
									</div>

									<div id="div">
                    
										<div id="number-of-apartments" class="col-md-4">
											<%= form.label :number_appartement %>
											<%= form.text_field :number_appartement, id: 'number_appartement' %>
										</div>
										<div id="number-of-floors" class="col-md-4">
											<%= form.label :number_floor %>
											<%= form.text_field :number_floor, id: 'number_floor' %>
										</div>
										<div id="number-of-basements" class="col-md-4">
											<%= form.label :number_basement %>
											<%= form.text_field :number_basement, id: 'number_basement' %>
										</div>
										<div id="number-of-companies" class="col-md-4">
											<%= form.label :number_compagny %>
											<%= form.text_field :number_compagny, id: 'number_compagny' %>
										</div>
										<div id="number-of-corporations" class="col-md-4">
											<%= form.label :number_corporate %>
											<%= form.text_field :number_corporate, id: 'number_corporate' %>
										</div>
										<div id="number-of-elevators" class="col-md-4">
											<%= form.label :number_elevator %>
											<%= form.text_field :number_elevator, id: 'number_elevator' %>
										</div>
										<div id="number-of-parking-spots" class="col-md-4">
											<%= form.label :number_parking %>
											<%= form.text_field :number_parking, id: 'number_parking' %>
										</div>
										<div id="maximum-occupancy" class="corporateChanger col-md-4">
											<%= form.label :max_occupancy %>
											<%= form.text_field :max_occupancy, id: 'max_occupancy' %>
										</div>
										<div id="business-hours" class="col-md-4">
											<%= form.label :business_hour %>
											<%= form.text_field :business_hour, id: 'business_hour' %>
										</div>
									</div>
								</fieldset>

							<!-- FORM RADIO BUTTON -->

								<div style="margin-top: 50px;" class="priceShow">
									Number of elevator shafts required : <span id="elevatorShafts">0</span>
								</div>


								<div id="elevator_type" class="priceShow"> 
									<div class="row" style="margin-top: 100px;">
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= form.label :Standard %>
											<%= form.radio_button :elevator_type, 'standard' %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= form.label :Premium %>
											<%= form.radio_button :elevator_type, 'premium' %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= form.label :Excelium %>
											<%= form.radio_button :elevator_type, 'excelium' %>
										</div>
									</div>
								</div>
							<!-- FORM RADIO BUTTON -->

							<!-- FORM RADIO VALUE -->

								<div id="quote" class="row" style="margin-top: 130px;">
									<div id="elevator-amount" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= form.label :ele_amount %>
										<%= form.text_field :ele_amount, id: 'ele_amount' %>
									</div>
									<div id="elevator-unit-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= form.label :ele_price_unit %>
										<%= form.text_field :ele_price_unit, id: 'ele_price_unit' %>
									</div>
									<div id="elevator-total-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= form.label :ele_total_price %>
										<%= form.text_field :ele_total_price, id: 'ele_total_price' %>
									</div>
									<div id="installation-fees" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= form.label :inst_fee %>
										<%= form.text_field :inst_fee, id: 'inst_fee' %>
									</div>
									<div id="final-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= form.label :final_price %>
										<%= form.text_field :final_price, id: 'final_price' %>
									</div>
									<div class="actions">
										<%= form.submit %>
									</div>
								</div>
						</div>
		</div>
</div>
						<!-- FORM RADIO VALUE -->
					

						<!-- FORM QUOTE -->


<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>


<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quote_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of Appartement</strong>
  <%= @quote.number_appartement %>
</p>


<div>
  <strong>Number of Floor</strong>
  <%= @quote.number_floor %>
</div>

<div>
  <strong>Number of Basement</strong>
  <%= @quote.number_basement %>
</div>

<div>
  <strong>Number of Compagny</strong>
  <%= @quote.number_compagny %>
</div>

<div>
  <strong>Number of Corporate</strong>
  <%= @quote.number_corporate %>
</div>

<div>
  <strong>Number of Elevator</strong>
  <%= @quote.number_elevator %>
</div>

<div>
  <strong>Number of Parking</strong>
  <%= @quote.number_parking %>
</div>

<div>
  <strong>Max of Occupancy</strong>
  <%= @quote.max_occupancy %>
</div>

<div>
  <strong>Business Hour</strong>
  <%= @quote.business_hour %>
</div>

<div>
  <strong>Elevator Amount</strong>
  <%= @quote.ele_amount %>
</div>

<div>
  <strong>Elevator Unit Price</strong>
  <%= @quote.ele_price_unit %>
</div>

<div>
  <strong>Elevator Total Price</strong>
  <%= @quote.ele_total_price %>
</div>

<div>
  <strong>Installation Fee</strong>
  <%= @quote.inst_fee %>
</div>

<div>
  <strong>Final Price</strong>
  <%= @quote.final_price %>
</div>



<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>