config/routes.rb
Rails.application.routes.draw do
  get 'company/new'
  get 'company/create'
  get 'addresses/new'
  get 'addresses/create'
  get 'leads/new'
  get 'leads/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  resources :quotes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'



  get "/home", to: "pages#home"
  get '/residential', to: 'pages#residential'
  get '/commercial', to: 'pages#commercial'
  get '/quote', to: 'pages#quote'



  get '/quotes' => 'quote#index'

  post '/quotes' => 'quotes#create'




  get 'employee/show'

  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    can :manage, :all
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :manage, :dashboard         # allow access to dashboard
    end
    if user.supervisor_role?
      can :manage, User
    end
  end
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    # can :read, Employee, :email, :last_name, :first_name :title => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
 
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
   
end

app/models/lead.rb
class Lead < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def has_role?(role)
    roles.include?(role)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def show
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end

    def quote
        
    end

    def residential

    end

    def commercial

    end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @quote = Quote.find(params[:id])
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create

    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:building_type, :number_appartement, :number_floor, :number_basement, :number_compagny, :number_corporate, :number_elevator, :number_parking, :max_occupancy, :business_hour, :building_prices, :elevator_type, :ele_amount, :ele_price_unit, :ele_total_price, :inst_fee, :final_price)
    end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Elevator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
		
		<%# <link rel="icon" href="./assets/image/icon-page.png"> %>
		



		<script>var plugin_path = 'assets/plugins/';</script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	
		<!-- CORE CSS -->
		<%# <link href="app/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" /> %>
		<%# <link href="./app/assets/stylesheets/style.css" rel="stylesheet" type="text/css" /> %>
		
	

		<!-- REVOLUTION SLIDER -->
		<%# <link href="app/assets/plugins/slider.revolution/css/extralayers.css" rel="stylesheet" type="text/css" /> %>
		<%# <link href="app/assets/plugins/slider.revolution/css/settings.css" rel="stylesheet" type="text/css" /> %>

		<!-- THEME CSS -->
		<%# <link href="app/assets/stylesheets/essentials.css" rel="stylesheet" type="text/css" /> %>
		<%# link href="assets/stylesheets/layout.css" rel="stylesheet" type="text/css" /> %>
		<%= stylesheet_link_tag "application" %>
		
	

		

		<!-- PAGE LEVEL SCRIPTS -->
		<%# <link href="app/assets/stylesheets/header-1.css" rel="stylesheet" type="text/css" />
		<link href="app/assets/stylesheets/color_scheme/blue.css" rel="stylesheet" type="text/css" id="color_scheme" /> %>


  </head>


  <body class="smoothscroll enable-animation">

	
			<!-- wrapper -->
		<div id="wrapper">

			<!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!

				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->

			
			<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					
					
						<div class="container">

							<!-- Mobile Menu Button -->
							<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
								<i class="fa fa-bars"></i>
							</button>

							<!-- Logo -->
							<a class="logo float-left scrollTo" href="#top">
								<%# <img src="./assets/image/R2.png" alt="" /> %>
								<%= image_tag("R2.png") %>
							</a>

							<!-- 
								Top Nav 
								
								AVAILABLE CLASSES:
								submenu-dark = dark sub menu
							-->
					
							<div id="home" class="navbar-collapse collapse float-right nav-main-collapse submenu-dark" >
								<nav class="nav-main">

									<!-- 
										.nav-onepage
										Required for onepage navigation links
										
										Add .external for an external link!
									-->
									
									<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
										
										<li class="active"><!-- HOME -->
											<a id="home-nav" href="/" style="display: flex; align-items: center;">
												HOME
											</a>
										</li>
										<li class="nav-item dropdown"><!-- SERVICES -->
											<a class="nav-link dropdown-toggle" href="/#services" data-bs-toggle="dropdown" style="display: flex; align-items: center;">SERVICES </a>
											 <ul class="dropdown-menu bg-white" style="border: none;">
											   <li><a class="dropdown-item" href="./residential" style="color: black;" >RESIDENTIAL</a></li>
											   <li><a class="dropdown-item" href="./commercial" style="color: black;" >COMMERCIAL</a></li>
											   <li><a class="dropdown-item" href="./quotes" style="color: black;" >GET QUOTE</a></li>
											 </ul>
										 </li>
										<li><!-- PORTFOLIO -->
											<a id="portfolio-nav" href="/#portfolio" style="display: flex; align-items: center;" >
												PORTFOLIO
											</a>
										</li>
										<li><!-- NEWS -->
											<a id="news-nav" href="/#news" style="display: flex; align-items: center;">
												NEWS
											</a>
										</li>
										<li><!-- CLIENTS -->
											<a id="clients-nav" href="/#clients" style="display: flex; align-items: center;">
												CLIENTS
											</a>
										</li>
										<li><!-- CONTACT -->
											<a id="contact-nav" href="/#contact" style="display: flex; align-items: center;">
												CONTACT
											</a>
										</li>
									
										
											<% if user_signed_in? %>
												<li class="nav-item dropdown" style="margin-left: 100px"><!-- PROFILE -->
													<a class="nav-link dropdown-toggle" id="btnAccount" data-bs-toggle="dropdown" style="display: flex; align-items: center;">PROFILE </a>
													<ul class="dropdown-menu bg-white" style="border: none;">
														<li><a class="dropdown-item" ><%= link_to('Logout', destroy_user_session_path,  :method => :delete, :style=>'color: black;' )%> </a></li>
													</ul>
												</li>
												<% if current_user.superadmin_role? || current_user.supervisor_role? %>
													<li><a class="dropdown-item" style="color: black;" <%= link_to 'Admin', rails_admin_path %> </a></li>
												<% end %>
											<% elsif !user_signed_in? %>
										
												<li class="nav-item dropdown" style="margin-left: 100px"><!-- ACCOUNT -->
													<a class="nav-link dropdown-toggle" id="btnAccount" data-bs-toggle="dropdown" style="display: flex; align-items: center;">ACCOUNT </a>
													<ul class="dropdown-menu bg-white" style="border: none;">
														<li><a class="dropdown-item" style="color: black;" <%= link_to 'Login', new_user_session_path %> </a></li>
														<li><a class="dropdown-item"  style="color: black;" <%= link_to 'Sign Up', new_user_registration_path %>  </a></li>
														<%# <li><a class="dropdown-item" href="./quote" style="color: black;" >GET QUOTE</a></li> %>
													</ul>
												</li>
											<% end %>		
								
									</ul>
									

								</div>

								</nav>
							</div>

						
				
				</header>
			
				<!-- /Top Nav -->

			</div>

    <%= yield %>

  <!-- FOOTER -->
			<footer id="footer">
				<div class="container">


					<div class="row">

						<!-- col #1 -->
						<div class="col-md-8">

							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
								We have the conviction that we create the most innovative and reliable products on the market. Contact us today for any questions you might have.

							</p>
							<h2>(418) 555-1234</h2>
						</div>
						<!-- /col #1 -->

						<!-- col #2 -->
						<div class="col-md-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

							<!-- Newsletter Form -->
							<p>Subscribe to Our Newsletter to get Important News & Offers</p>

							<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="growHover btn btn-blue" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->


						</div>
						<!-- /col #2 -->

					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li><a href="#">Terms &amp; Conditions</a></li>
							<li>&bull;</li>
							<li><a href="#">Privacy</a></li>
						</ul>
						&copy; All Rights Reserved, Company LTD
					</div>
				</div>

		
			</footer>
			<!-- /FOOTER -->

		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>



		<!-- JAVASCRIPT FILES -->
		
	<%#	<script src="assets/plugins/jquery/jquery-3.3.1.min.js"></script> %>
		<%# <script src="assets/js/quote.js"></script> %>
		<%# <script src="assets/js/scripts.js"></script> %>

		
		

		<!-- REVOLUTION SLIDER -->
		<%# <script src="assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script> %>
		<%# <script src="assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script> %>
		<%# <script src="assets/js/view/demo.revolution_slider.js"></script> %>

		<!-- PAGELEVEL SCRIPTS -->
		<%# <script src="assets/js/contact.js"></script> %>

		<!-- 
			GMAP.JS 
			http://hpneo.github.io/gmaps/
		-->
		<%# <script src="//maps.google.com/maps/api/js?key=AIzaSyCqCn84CgZN6o1Xc3P4dM657HIxkX3jzPY"></script> %>
		<%# <script src="assets/plugins/gmaps.js"></script> %>

		
		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>


	<%# 	<!-- PRELOADER -->
		<div id="preloader">
			<div class="inner">
				<span class="loader"></span>
			</div>
		</div><!-- /PRELOADER --> %>



  </body>
</html>

app/views/pages/commercial.html.erb
<!-- wrapper -->
		<div id="wrapper">


			<hr class="m-0" /><!-- 1px line separator -->


			<!-- BUTTON CALLOUT -->
			<a href="./index.html#contact" class="btn btn-xlg btn-danger	 fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Did Rocket Elevator convinced you? 
					<strong>Contact us &raquo;</strong>
				</span>
			</a>
			<!-- /BUTTON CALLOUT -->

			<!-- COMMERCIAL CONTENT -->

			<section id="commercial" >
				<div class='container'>
					<div class="heading-title heading-dotted text-center">
						<h1>Commercial Solutions</h1>
					</div>
					<p class="col-md-12">Whether you need to move a few people a few floors or thousands of people over a hundred floors
						, thyssenkrupp Elevator has the right solution for your building. No matter your priority, our elevators deliver 
						reliability, shorter ride times and less congestion.</p>
				</div>
				<div class='container' style='display: flex; margin-top: 100px;'>
					<div class="col-md-6">
						<%= image_tag("NewJerseyAvenue.jpg", width:"100%", height:"350px") %>
						<%# <img src="./assets/image/NewJerseyAvenue.jpg" alt="New Jersey Avenue" style="width: 100%; max-height: 350px;" /> %>
					</div>
					<div class="col-md-6">
						<h1 class="text-center">300 New Jersey Avenue, NW, Washington, D.C.</h1>
						<p> The historic status of this building meant extremely restricting guidelines for an expansion project. 
							Renowned architect Richard Rogers came up with a plan to connect three separate structures into one with an open-air elevator shaft 
							featuring glass walkways. ThyssenKrupp Elevators Americas designed, manufactured and installed the elevators for this project.
							 Some design aspects include an exposed red elevator track and scenic car with a seamless glass wall and ceiling configuration. 
							 Read more about the project in the Washington Post.</p>
					</div>
				</div>
				<div class='container' style='display: flex; margin-top: 100px;'>
					<div class="col-md-6">
						<h1 class="text-center">World Financial Center, New York, New York</h1>
						<p>mproving energy conservation was the goal of the World Financial Center’s modernization project. 
							A total of 96 elevators were updated as part of a $250 million renovation endeavor. thyssenkrupp Elevator modernizations 
							achieve the largest potential for efficiency by reducing the energy used to operate the elevators. The project also marks 
							the first large-scale modernization in the region to feature thyssenkrupp Elevator’s Destination Dispatch, which directs passengers 
							to the elevator that will get them to their destination in the shortest travel time. This practice can reduce time to destination 
							by up to 30% compared to standard elevator control. Our energy-saving feature and equipment, combined with our long-term service 
							contract, support sustainability efforts and set new standards for eco-efficiency. In fact, One World Financial Center was recently
							 certified LEED Gold.</p>
					</div>
					<div class="col-md-6">
						<%= image_tag("oneWorldTrade.jpg", width:"100%", height:"470px") %>
						<%# <img src="./assets/image/oneWorldTrade.jpg" alt="/One World Trade" style="width: 100%; max-height: 470px;" /> %>
					</div>
				</div>

				<div class="container" style="display: flex; justify-content: center; margin-top: 100px;">		
					<a href="./quotes" class="growHover btn btn-blue btn-lg">
						Get A Quote
					</a> 
			</div>
				
			</section>
			<!-- /COMMERCIAL CONTENT -->

app/views/pages/quote.html.erb
<!-- wrapper -->
<div id="ctnWhite"> 
		<div id="wrapper">

			<hr class="m-0" /><!-- 1px line separator -->


			<!-- BUTTON CALLOUT -->
			<a href="./index.html#contact" class="btn btn-xlg btn-danger	 fs-20 fullwidth m-0 rad-0 p-40">
				<span class="font-lato fs-30">
					Did Rocket Elevator convinced you? 
					<strong>Contact us &raquo;</strong>
				</span>
			</a>
			<!-- /BUTTON CALLOUT -->

		
						<!-- FORM -->
						<div class="col-md-10 col-sm-4" style="margin: 100px 8%;">

							<h3 style="text-align: center;">A Work Faithful To The Wait</h3>

							<!-- Alert Success -->
							<div id="alert_success" class="alert alert-success mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Thank You!</strong> Your message successfully sent!
							</div><!-- /Alert Success -->


							<!-- Alert Failed -->
							<div id="alert_failed" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>[SMTP] Error!</strong> Internal server error!
							</div><!-- /Alert Failed -->


							<!-- Alert Mandatory -->
							<div id="alert_mandatory" class="alert alert-danger mb-30">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Sorry!</strong> You need to complete all mandatory (*) fields!
							</div><!-- /Alert Mandatory -->



							
							<!-- FORM QUOTE -->
							<%= form_with(model: @Quote, local: true, :method => "post") do |form| %>
								<fieldset>
									<input type="hidden" name="action" value="contact_send" />

									<div class="row">
										<div class="col-md-12">
											<label for="contact_department">Department</label>
											
											<select id="building_type" class="form-control pointer" name="contact[department]">
												<option value="select">--- Select ---</option>
												<option value="residential">Residential</option>
												<option value="commercial">Commercial</option>
												<option value="corporate">Corporate</option>
												<option value="hybrid">Hybrid</option>
											</select>
										</div>
									</div>

									<div id="div">
										<div id="number-of-apartments" class="col-md-4">
											<%= label_tag  "name_id", "N. of Appartements *" %>
											<%= number_field_tag "number_appartement", "0", placeholder: "N. of Appartements", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-floors" class="col-md-4">
											<%= label_tag  "name_id", "N. of Floor *" %>
											<%= number_field_tag "number_floor", "0", placeholder: "N. of Floor", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-basements" class="col-md-4">
											<%= label_tag  "name_id", "N. of Basements *" %>
											<%= number_field_tag "number_basement", "0", placeholder: "N. of Basements", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-companies" class="col-md-4">
											<%= label_tag  "name_id", "N. of Compagnies *" %>
											<%= number_field_tag "number_compagny", "0", placeholder: "N. of Compagnies", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-corporations" class="col-md-4">
											<%= label_tag  "name_id", "N. of Corporate *" %>
											<%= number_field_tag "number_corporate", "0", placeholder: "N. of Corporate", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-elevators" class="col-md-4">
											<%= label_tag  "name_id", "N. of Elevator Cages *" %>
											<%= number_field_tag "number_elevator", "0", placeholder: "N. of Elevator Cages", class: "form-control", min: "0" %>
										</div>
										<div id="number-of-parking-spots" class="col-md-4">
											<%= label_tag  "name_id", "N. of Parking Spots *" %>
											<%= number_field_tag "number_parking", "0", placeholder: "N. of Parking Spots", class: "form-control", min: "0" %>
										</div>
										<div id="maximum-occupancy" class="corporateChanger col-md-4">
											<%= label_tag  "name_id", "N. of Occupancy by stage *" %>
											<%= number_field_tag "max_occupancy", "0", placeholder: "N. of Occupancy by stage", class: "form-control", min: "0" %>
										</div>
										<div id="business-hours" class="col-md-4">
											<%= label_tag  "name_id", "N. of Hours of Building Activity *" %>
											<%= number_field_tag "business_hour", "0", placeholder: "N. of Hours of Building Activity", class: "form-control", min: "0" %>
										</div>
									</div>
								</fieldset>

							<!-- FORM RADIO BUTTON -->

								<div style="margin-top: 50px;" class="priceShow">
									Number of elevator shafts required : <span id="elevatorShafts">0</span>
								</div>


								<div id="elevator_type" class="priceShow"> 
									<div class="row" style="margin-top: 100px;">
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= label_tag  "name_id", "Standard" %>
											<%= radio_button_tag "elevator_type", "standard" %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= label_tag  "name_id", "Premium" %>
											<%= radio_button_tag "elevator_type", "premium" %>
										</div>
										<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
											<%= label_tag  "name_id", "Excelium" %>
											<%= radio_button_tag "elevator_type", "excelium" %>
										</div>
									</div>
								</div>
							<!-- FORM RADIO BUTTON -->

							<!-- FORM RADIO VALUE -->

								<div id="quote" class="row" style="margin-top: 130px;">
									<div id="elevator-amount" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= label_tag  "name_id", "N. of Elevator" %>
										<%= text_field_tag "ele_amount" %>
									</div>
									<div id="elevator-unit-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= label_tag  "name_id", "Elevator Unit Price" %>
										<%= text_field_tag "ele_price_unit" %>
									</div>
									<div id="elevator-total-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= label_tag  "name_id", "Elevator Total Price" %>
										<%= text_field_tag "ele_total_price" %>
									</div>
									<div id="installation-fees" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= label_tag  "name_id", "Installation Fees" %>
										<%= text_field_tag "inst_fee" %>
									</div>
									<div id="final-price" class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= label_tag  "name_id", "Final Price" %>
										<%= text_field_tag "final_price" %>
									</div>
									<div class="col-md-4" style="display: flex; flex-direction: column; align-items: center;">
										<%= submit_tag "Save Quote" %>
									</div>
								</div>
							<%end%>
						</div>
		</div>
</div>
						<!-- FORM RADIO VALUE -->
					

						<!-- FORM QUOTE -->